language: csharp
sudo: required
services:
  - docker

before_install:
  - pip install -U docker-compose
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get -y install dotnet-dev-1.0.0-preview2-003121
  - dotnet --info

install:
  - dotnet restore
  - dotnet build src/MoviesApi/project.json
  - dotnet build test/MoviesApi.Tests/project.json

script:
  - cd test/MoviesApi.Tests && dotnet test && cd ../..
  - docker-compose -f src/MoviesApi/docker-compose.yml up -d --build --force-recreate
  - docker-compose -f src/MoviesApi/docker-compose.yml ps

after_script:
  - docker-compose -f src/MoviesApi/docker-compose.yml stop
  - docker-compose -f src/MoviesApi/docker-compose.yml rm -f