version: '2'

services:

  # mongo
  mongo-seed:
    build: ./mongo-seed
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    links:
      - mongo
  mongo:
    container_name: 'angularmovies-db'
    image: mongo:3.2
    volumes:
      - /data/db
    ports:
      - "27017:27017"
    command: --smallfiles